name: le-bot-frontend CI/CD

on:
  push:
    branches: [ ci-*, main ]
    tags: [ pre*, v* ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.git-info.outputs.commit-hash }}
      base-name: ${{ steps.assemble-base-name.outputs.base-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          COMMIT_HASH=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
      - name: Assemble package base name
        id: assemble-base-name
        shell: bash
        run: |
          BASE_NAME=LeBotFrontend_${{ steps.git-info.outputs.commit-hash }}_#${{ GITHUB.RUN_NUMBER }}
          echo "base-name=$BASE_NAME" >> $GITHUB_OUTPUT

  build-web:
    runs-on: ubuntu-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./dist/pwa
      RELEASE_FOLDER: ./release
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies and Build
        run: |
          bun install
          DEPLOY_GITHUB_PAGE=true bun run build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ${{ env.OUTPUT_FOLDER }}
          keep_history: false
          target_branch: gh-pages

  build-elysia:
    runs-on: ubuntu-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./dist/pwa
      RELEASE_FOLDER: ./release
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies and Build
        run: |
          bun install
          DEPLOY_ELYSIA=true bun run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: le-bot-frontend_${{ needs.get-info.outputs.commitHash }}_${{ GITHUB.RUN_NUMBER }}_artifacts
          path: |
            ${{ env.OUTPUT_FOLDER }}
      - name: Prepare for release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FOLDER }}
          7z a -tzip ${{ env.RELEASE_FOLDER }}/le-bot-frontend.zip "${{ env.OUTPUT_FOLDER }}/*"
      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ env.RELEASE_FOLDER }}/le-bot-frontend.zip
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre') }}